### ISSUE TITLE
Potential information loss

### ISSUE THREAD

**Issue by GeneZC** [bfshi/scaling_on_scales#15]
I am new to image processing.

It is found that common image processings (e.g., CLIP-ViT) would first resize (most likely sub-sample) the original images.

And S2 would interpolate (or up-sample) these processed images.

I am wondering whether this first-sub-then-up op would lead to any information loss of the original images, compared to directly operate the original images with the idea of S2?

**Comment by bfshi** [comment]
Yes you are right. There will be information loss.

The reason we first subsample the high-res image and then upsample back is to ensure a fair comparison to model size scaling. See Section 3.1 of the paper:
![image](https://github.com/user-attachments/assets/2b0955a9-0324-4df8-9483-959cfe54f2f3)

In practice, directly performing S2 on the origin high-res image would be the best. See the last part of [Quickstart](https://github.com/bfshi/scaling_on_scales#quickstart):
![image](https://github.com/user-attachments/assets/773d11bb-a4de-4d01-b9eb-8734ad08825b)

**Comment by GeneZC** [comment]
ic, thanks~
